### ISSUE TITLE
class not found exeption com/jayway/jsonpath/Predicate

### ISSUE THREAD

**Issue by revington** [jayway/JsonPath#112]
Tried to use this library.
I'm using 2.0 with maven, dependency in `pom.xml` looks like
```
....
 <dependency>                              
     <groupId>com.jayway.jsonpath</groupId>
     <artifactId>json-path</artifactId>    
     <version>2.0.0</version>              
 </dependency>                             
....
```
Code 
```
 22 public class App {                                                           
 23     public static class TokenizerMapper                                      
 24             extends Mapper<Object, Text, Text, IntWritable> {                
 25         private final static IntWritable one = new IntWritable(1);           
 26         private Text word = new Text();                                      
 27                                                                              
 28         public void map(Object key, Text value, Context context)             
 29                 throws IOException, InterruptedException {                   
 30             String text = JsonPath.read(value.toString(), "$.d3Params.cr");  
 31                                                                              
 32             word.set(text);                                                  
 33             context.write(word, one);                                        
 34         }                                                                    
 35     }                                                                        
```
And here is the exception
```
java.lang.Exception: java.lang.NoClassDefFoundError: com/jayway/jsonpath/Predicate
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.NoClassDefFoundError: com/jayway/jsonpath/Predicate
        at com.d3media.app.App$TokenizerMapper.map(App.java:30)
        at com.d3media.app.App$TokenizerMapper.map(App.java:23)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:784)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.Predicate
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```
Also, I'm new to java so maybe doing something silly.

**Comment by revington** [comment]
Never mind, issue was not related with JsonPath but the way I run hadoop

**Comment by kvinay729** [comment]
So what was the exact issue? I am facing the same while using JSON Path Extraction/Assertion plugins in Jmeter.

**Comment by revington** [comment]
Sorry @kvinay729 it has been a long time I do not remember this issue

**Comment by basmussen** [comment]
I had the java.lang.NoClassDefFoundError: com/jayway/jsonpath/Predicate by using json-path-assert 2.4.0. It comes with a json-path 0.8.1 and raise the NoClassDefFoundError

**Issue**
```
<dependency> 
  <groupId>com.jayway.jsonpath</groupId>  
  <artifactId>json-path-assert</artifactId>  
  <version>2.4.0</version>  
  <scope>test</scope> 
</dependency>

```

**Solution**

Use the similar version of json-path.

```
  <dependency> 
    <groupId>com.jayway.jsonpath</groupId>  
    <artifactId>json-path-assert</artifactId>  
    <version>2.4.0</version>  
    <scope>test</scope> 
  </dependency>  
  <dependency> 
    <groupId>com.jayway.jsonpath</groupId>  
    <artifactId>json-path</artifactId>  
    <version>2.4.0</version>  
    <scope>test</scope> 
  </dependency> 
```

**Comment by hendisantika** [comment]
I have the same issue. Then I try @basmussen solution but It didn't resolve my issue.

Any suggest?
Thanks
