### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI

### ISSUE THREAD

**Issue by hooperbloob** [jayway/JsonPath#159]
I've put together a simple TestNG exercise using JsonPath but it doesn't complete the parsing to get the ReadContext owing to a class its unable to load:

java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI
	at com.jayway.jsonpath.internal.DefaultsImpl.<init>(DefaultsImpl.java:17)
	at com.jayway.jsonpath.internal.DefaultsImpl.<clinit>(DefaultsImpl.java:15)
	at com.jayway.jsonpath.Configuration.getEffectiveDefaults(Configuration.java:48)
	at com.jayway.jsonpath.Configuration.defaultConfiguration(Configuration.java:173)
	at com.jayway.jsonpath.internal.JsonContext.<init>(JsonContext.java:52)
	at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:596)

I'm using the suggested reference to 2.1.0 in my pom file.

Any suggestions?

**Comment by pengboyin** [comment]
i have same question.

**Comment by kallestenflo** [comment]
@pengboyin Looks like JsonSmart is missing on class path.

**Comment by ddwolf** [comment]
I encountered this error while I was running a junit test. I add json-smart and asm to my pom.xml, then the error dissapeared.

```xml
        <dependency>
            <groupId>net.minidev</groupId>
            <artifactId>asm</artifactId>
            <version>1.0.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>net.minidev</groupId>
            <artifactId>json-smart</artifactId>
            <version>2.2.1</version>
            <scope>test</scope>
        </dependency>
```

**Comment by LiangZhang2017** [comment]
But How can I add the json-smart if I just use the jason-path-2.4.0.jar? Thanks a lot.

**Comment by LiangZhang2017** [comment]
> But How can I add the json-smart if I just use the jason-path-2.4.0.jar? Thanks a lot.

I have already figures it out. Yes, when the json-smart, asm and accessors-smart are added. Then the error also disapear. Thanks also.

**Comment by LiangZhang2017** [comment]
> But How can I add the json-smart if I just use the jason-path-2.4.0.jar? Thanks a lot.

I have already figures it out. Yes, when the json-smart, asm and accessors-smart are added. Then the error also disapear. Thanks also.

**Comment by aahassen** [comment]
I am having similar errors even after adding the above mentioned dependencies to my spring-boot pom file. My app was always working all the sudden I started seeing these error while running my spring boot app from eclipse.

	```
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$fcffdac2.requestMappingHandlerAdapter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: net.minidev.json.writer.JsonReaderI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 common frames omitted
```
