### ISSUE TITLE
Filter: [?] can not be applied to primitives.

### ISSUE THREAD

**Issue by marcingrzejszczak** [jayway/JsonPath#205]
Having the following json:

```
{
                "path" : "/api/12",
                "correlationId" : 123456
}
```

when I apply the following JSON Path

```
$[?(@.path =~ /^\/api\/[0-9]{2}$/)]
```

like this (`parsedJson` is a `DocumentContext`):

```
parsedJson.read(jsonPathString, JSONArray.class).isEmpty()
```

I get:

```
com.jayway.jsonpath.InvalidPathException: Filter: [?] can not be applied to primitives. Current context is: 
                {
                    "path" : "/api/12",
                    "correlationId" : 123456
                }
            

	at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:66)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:158)
```

If you provide that JSON here: http://jsonpath.herokuapp.com/?path=$[?(@.path%20=~%20/^\/api\/[0-9]{2}$/)] a result is presented. I'm pretty sure that it used to work with JSON Path 2.0.0

**Comment by marcingrzejszczak** [comment]
My bad.. I've done a bug on myside... Sorry :P

**Comment by vtahunou** [comment]
> My bad.. I've done a bug on myside... Sorry :P

@marcingrzejszczak Could you please provide correct solution in case you fixed it on youe side?

**Comment by marcingrzejszczak** [comment]
Oh man, I don't remember how I fixed this one, sorry.
