### ISSUE TITLE
lenght() method is not working

### ISSUE THREAD

**Issue by ravikirankatneni** [jayway/JsonPath#210]
Hi,

Trying to execute Jpath

String jpath = "$..book.length()";

DocumentContext documentContext = JsonPath.parse(modifiedJsonResponse);
documentContext.read(jpath);

with data 

{    "store": {         "book": [             {                  "category": "reference",                 "author": "Nigel Rees",                "title": "Sayings of the Century",                "price": 8.95            },            {                "category": "fiction",                "author": "Evelyn Waugh",                "title": "Sword of Honour",                "price": 12.99            },            {                "category": "fiction",                "author": "Herman Melville",                "title": "Moby Dick",                "isbn": "0-553-21311-3",                "price": 8.99            },            {                "category": "fiction",                "author": "J. R. R. Tolkien",                "title": "The Lord of the Rings",                "isbn": "0-395-19395-8",                "price": 22.99            }        ],        "bicycle": {           "color": "red",            "price": 19.95        }    },    "expensive": 10}

I am getting following exception when I try get the length of array

Exception in thread "main" com.jayway.jsonpath.PathNotFoundException: Property ['length()'] not found in path $['store']['book']
    at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:41)
    at com.jayway.jsonpath.internal.token.PathToken.handleObjectProperty(PathToken.java:71)
    at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:44)
    at com.jayway.jsonpath.internal.token.ScanPathToken.walkObject(ScanPathToken.java:72)
    at com.jayway.jsonpath.internal.token.ScanPathToken.walk(ScanPathToken.java:37)
    at com.jayway.jsonpath.internal.token.ScanPathToken.walkObject(ScanPathToken.java:80)
    at com.jayway.jsonpath.internal.token.ScanPathToken.walk(ScanPathToken.java:37)
    at com.jayway.jsonpath.internal.token.ScanPathToken.evaluate(ScanPathToken.java:32)
    at com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:53)
    at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:53)
    at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:61)
    at com.jayway.jsonpath.JsonPath.read(JsonPath.java:178)
    at com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:146)
    at com.jayway.jsonpath.internal.JsonReader.read(JsonReader.java:135)
    at com.opentext.test.impl.DominoAccessConnection.main(DominoAccessConnection.java:53)

**Comment by kallestenflo** [comment]
What version are u using? 2.2?

**Comment by ravikirankatneni** [comment]
Version is 2.0

**Comment by kallestenflo** [comment]
can you upgrade to 2.2?

**Comment by bzhvince** [comment]
The issue is still present even with 2.2.0.

**Comment by susnigdha1** [comment]
Hi...I am using version 2.0.0 and still facing this issue, length() method is not working. Could you please let me know if the issue has been resolved?

**Comment by jochenberger** [comment]
I cannot reproduce this in http://jsonpath.herokuapp.com/

**Comment by kallestenflo** [comment]
Can not reproduce.
