### ISSUE TITLE
InvalidPathException when compiling the following json

### ISSUE THREAD

**Issue by alextsc** [jayway/JsonPath#231]
I have trouble compiling the following json in JsonPath

```
{
    "pagination": {
        "page": 0,
        "items_per_page": 10
    },
    "artifacts": ["one", "two", "three"]
}
```

As far as I can see it's valid, however JsonPath can't read it and throws an exception:

```
Exception in thread "main" com.jayway.jsonpath.InvalidPathException: Use bracket notion ['my prop'] if your property contains blank characters. position: 2
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:184)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:118)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:54)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:69)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at Example.main(Example.java:14)
	//...
```

Note that I'm not accessing any property just yet, I'm just calling compile. This little sample application reproduces the issue:

```
import com.jayway.jsonpath.JsonPath;

public class Example {

    public static void main(String[] args) {
        String input = "{\n" +
                "    \"pagination\": {\n" +
                "        \"page\": 0,\n" +
                "        \"items_per_page\": 10\n" +
                "    },\n" +
                "    \"artifacts\": [\"one\", \"two\", \"three\"]\n" +
                "}";

        JsonPath.compile(input);
    }
}
```

I'm using JsonPath 2.2.0 on Windows 10 x64. Additionally stripping all whitespace from the json works just fine (which is expected since it seems to get hung up on whitespace somewhere). 

Am I missing something here or is this indeed a bug?

**Comment by jlolling** [comment]
I guess this is not the path instead it is the document itself?

**Comment by alextsc** [comment]
Yeah thats what it was. Definitely not my proudest moment. Sorry for the unneccessary noise.

**Comment by jlolling** [comment]
Don’t worry. Shit happens… Nothing damaged, only your pride ;-)
