### ISSUE TITLE
JsonPath with lambda expressions behaves differently than heroku app

### ISSUE THREAD

**Issue by vasanthykolluri** [jayway/JsonPath#238]
**Data:**
[{"store": {"book": [{"category": "reference","pages": {"count" : 10}}]},"source":"me"}]                        

**Expr:**
$[?(@.source=='me')].store.book[?(@.category == 'reference')].pages.count

The above expression works fine on the http://jsonpath.herokuapp.com.

But with JsonPath.read, I get an InvalidPathException.

**Code:**
        _String json="[{\"store\": {\"book\": [{\"category\": \"reference\",\"pages\": {\"count\" : 10}}]},\"source\":\"me\"}]";
        JsonElement root = new JsonParser().parse(json);
        String jsonPath = "$[?(@.source=='me')].store.book[?(@.category == 'reference')].pages.count";
        JsonPath.read(root, jsonPath);_

**Stack Trace:**
com.jayway.jsonpath.InvalidPathException: Filter: [?]['store']['book'][?]['pages']['count'] can not be applied to primitives. Current context is: [{"store":{"book":[{"category":"reference","pages":{"count":10}}]},"source":"me"}]
    at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:66)
    at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
    at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
    at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
    at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
    at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
    at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
    at com.jayway.jsonpath.JsonPath.read(JsonPath.java:488)

**Comment by jochenberger** [comment]
You're not supported to parse the JSON string yourself, JsonPath will take care of that. Just use:
```java
JsonPath.read(jsonString, jsonPath);
```
