### ISSUE TITLE
spring boot 1.4.0 integrate conflict

### ISSUE THREAD

**Issue by wzlee** [jayway/JsonPath#240]
`Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: com.jayway.jsonpath.JsonPath.compile(Ljava/lang/String;[Lcom/jayway/jsonpath/Filter;)Lcom/jayway/jsonpath/JsonPath;
    at us.codecraft.webmagic.selector.JsonPathSelector.<init>(JsonPathSelector.java:23)
    at com.wzlee.search.processor.CommentProcessor.process(CommentProcessor.java:17)
    at us.codecraft.webmagic.Spider.processRequest(Spider.java:415)
    at us.codecraft.webmagic.Spider$1.run(Spider.java:322)
    at us.codecraft.webmagic.thread.CountableThreadPool$1.run(CountableThreadPool.java:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by PriSt7** [comment]
,?how it fixed
