### ISSUE TITLE
MappingException when reading to boolean type

### ISSUE THREAD

**Issue by odlp** [jayway/JsonPath#280]
When reading a boolean value from JSON, the `JsonSmartMappingProvider` throws an exception if boolean type is passed as an argument.

## Example test:

```java
public class JaywayTest {

    @Test
    public void booleanMapping() {
        String jsonString = "{\"boolean_value\": true}";
        DocumentContext json = JsonPath.parse(jsonString);

        assertTrue((boolean)json.read("$.boolean_value")); // PASSES
        assertTrue(json.read("$.boolean_value", boolean.class)); // java.lang.NullPointerException
    }
}
```

## Exception thrown:
```
com.jayway.jsonpath.spi.mapper.MappingException: java.lang.NullPointerException

	at com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider.map(JsonSmartMappingProvider.java:84)
	at com.jayway.jsonpath.internal.JsonContext.convert(JsonContext.java:192)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:158)
```

The [JsonSmartMappingProvider](https://github.com/jayway/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/spi/mapper/JsonSmartMappingProvider.java) doesn't have a mapping for the boolean type.

Is this expected behaviour? Should the read value always be cast, as per the first assertion, rather than passing the type as an argument?

**Comment by odlp** [comment]
@kallestenflo hope this PR does the trick :)
