### ISSUE TITLE
Microlog4android conflicts with JsonPath

### ISSUE THREAD

**Issue by NikolayKul** [jayway/JsonPath#282]
Hello!
I use [microlog4android-1.0.0.jar](https://github.com/johanlkarlsson/microlog4android) in my project.
Adding JsonPath like this:
```gradle
compile('com.jayway.jsonpath:json-path:2.2.0') {
  exclude group: 'org.ow2.asm', module: 'asm'
}
```
cause an error:
```java
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/slf4j/helpers/BasicMarker.class
```
I tried to exclude `slf4j`  from JsonPath:
```gradle
compile('com.jayway.jsonpath:json-path:2.2.0') {
  exclude group: 'org.ow2.asm', module: 'asm'
  exclude group: 'org.slf4j', module: 'slf4j-api'
}
```
but it throws another error when I call `Criteria.where(..)`:
```java
java.lang.UnsupportedOperationException: trace(String, Object, Object) is not implemented yet
  at org.slf4j.impl.MicrologLoggerAdapter.trace(MicrologLoggerAdapter.java:54)
  at com.jayway.jsonpath.internal.filter.ValueNode$PathNode.<init>(ValueNode.java:770)
  at com.jayway.jsonpath.internal.filter.ValueNode$PathNode.<init>(ValueNode.java:763)
  at com.jayway.jsonpath.internal.filter.ValueNode.toValueNode(ValueNode.java:176)
  at com.jayway.jsonpath.Criteria.where(Criteria.java:98)
  ... // my stuff
```
What should I do?

**Comment by kallestenflo** [comment]
Sounds like a problem with the org.slf4j.impl.MicrologLoggerAdapter implementation.
