### ISSUE TITLE
ClassNotFoundException for GSON provider when reading numbers (float, double, etc) in OSGI envrionment.

### ISSUE THREAD

**Issue by SupunS** [jayway/JsonPath#289]
GsonJsonProvider class use an internal class [LazilyParsedNumber](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/LazilyParsedNumber.java)  of GSON library, for unwrapping numbers. (See: https://github.com/jayway/JsonPath/blob/master/json-path/src/main/java/com/jayway/jsonpath/spi/json/GsonJsonProvider.java#L34).

But since [LazilyParsedNumber](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/internal/LazilyParsedNumber.java) is an internal class, it is not exported by the gson bundle, hence is not available in OSGI environment. As a result, when tries to read a number using json path in an osgi environment, following CNF exception is thrown:

```
Exception in thread "pool-5-thread-1" java.lang.NoClassDefFoundError: com/google/gson/internal/LazilyParsedNumber
	at com.jayway.jsonpath.spi.json.GsonJsonProvider.unwrapNumber(GsonJsonProvider.java:92)
	at com.jayway.jsonpath.spi.json.GsonJsonProvider.unwrap(GsonJsonProvider.java:82)
	at com.jayway.jsonpath.spi.json.GsonJsonProvider.getMapValue(GsonJsonProvider.java:172)
	at com.jayway.jsonpath.internal.path.PathToken.readObjectProperty(PathToken.java:121)
	at com.jayway.jsonpath.internal.path.PathToken.handleObjectProperty(PathToken.java:44)
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:79)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:164)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:151)
        ...
Caused by: java.lang.ClassNotFoundException: com.google.gson.internal.LazilyParsedNumber cannot be found by com.jayway.jsonpath.json-path_2.2.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
```

**Comment by steve-white** [comment]
Same issue here. We've had to comment some bits out and built locally to get around this since we're not using GSON - not ideal.
