### ISSUE TITLE
Values with spaces not working

### ISSUE THREAD

**Issue by ammar-khan** [jayway/JsonPath#291]
JSON used:
{"store":{"book":{"category":"reference","author":"Nigel Rees","title":"Sayings of the Century","price":8.95}},"expensive":10}

JSON Path: $.store.book.title

com.jayway.jsonpath.InvalidPathException: Use bracket notion ['my prop'] if your property contains blank characters. position: 51

	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:184)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:231)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:118)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:54)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:69)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.JsonPath.isPathDefinite(JsonPath.java:117)
	at com.disc_au.utilsimpl.JSONUtilsImpl.getJSONValue(JSONUtilsImpl.java:73)
	at com.disc_au.web.tags.util.GetJsonTag._getJsonValue(GetJsonTag.java:99)
	at com.disc_au.web.tags.util.GetJsonTagTest.DataTest(GetJsonTagTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by plastic-karma** [comment]
Hey, can you post the code snippet, where the exception is occurring? The exception happens, if you have white spaces in you path (not in your input).

I produced the following results with version 2.2.0:

no exception:
```
final String input = "{\"store\":{\"book\":{\"category\":\"reference\",\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"price\":8.95}},\"expensive\":10}";
final JsonPath compile = JsonPath.compile("$.store.book.title");
compile.read(input);
```

exception:
```
final String input = "{\"store\":{\"book\":{\"category\":\"reference\",\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"price\":8.95}},\"expensive\":10}";
final JsonPath compile = JsonPath.compile("$.store.bo ok.title");
compile.read(input);
```

no exception:
```
final String input = "{\"store\":{\"bo ok\":{\"category\":\"reference\",\"author\":\"Nigel Rees\",\"title\":\"Sayings of the Century\",\"price\":8.95}},\"expensive\":10}";
final JsonPath compile = JsonPath.compile("$.store.['bo ok'].title");
compile.read(input);
```

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed.

**Comment by kallestenflo** [comment]
Can not reproduce. Need the path to verify this and its not provided.
