### ISSUE TITLE
Not working with single array element

### ISSUE THREAD

**Issue by ammar-khan** [jayway/JsonPath#293]
JSON Used:
{"menu":{"id":"file","value":"File","popup":{"menuitem":[{"value":"New","onclick":"CreateNewDoc()"},{"value":"Open","onclick":"OpenDoc()"},{"value":"Close","onclick":"CloseDoc()"}]}}}

com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 31. Expected ?, ', 0-9, * 

	at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:607)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:137)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:231)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:118)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:54)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:69)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.JsonPath.isPathDefinite(JsonPath.java:117)
	at com.disc_au.utilsimpl.JSONUtilsImpl.getJSONValue(JSONUtilsImpl.java:73)
	at com.disc_au.web.tags.util.GetJsonTag._getJsonValue(GetJsonTag.java:99)
	at com.disc_au.web.tags.util.GetJsonTagTest.DataTest(GetJsonTagTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by plastic-karma** [comment]
What JSONPath expression did you use ?

**Comment by jochenberger** [comment]
@kallestenflo IMO this should be closed until someone provides instructions how to reproduce the issue.

**Comment by kallestenflo** [comment]
Come back with more info!
