### ISSUE TITLE
JsonPath annotation root path exception

### ISSUE THREAD

**Issue by mahmutGuru** [jayway/JsonPath#336]
Hi,

When we try to get the root as a field in the object, we get the error:

```
com.jayway.jsonpath.InvalidPathException: Path must not end with a '.' or '..'
	at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:607) ~[json-path-2.2.0.jar:2.2.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:66) ~[json-path-2.2.0.jar:2.2.0]
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101) ~[json-path-2.2.0.jar:2.2.0]
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467) ~[json-path-2.2.0.jar:2.2.0]
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:149) ~[json-path-2.2.0.jar:2.2.0]
	at com.fasterxml.jackson.contrib.jsonpath.DefaultJsonUnmarshaller.readValueFromJsonTree(DefaultJsonUnmarshaller.java:241) ~[json-unmarshaller-1.1.1.jar:?]
	at com.fasterxml.jackson.contrib.jsonpath.DefaultJsonUnmarshaller.performJsonPathUnmarshalling(DefaultJsonUnmarshaller.java:194) ~[json-unmarshaller-1.1.1.jar:?]
	at com.fasterxml.jackson.contrib.jsonpath.DefaultJsonUnmarshaller.recursivelyProcessAllFields(DefaultJsonUnmarshaller.java:106) ~[json-unmarshaller-1.1.1.jar:?]
	at com.fasterxml.jackson.contrib.jsonpath.DefaultJsonUnmarshaller.unmarshal(DefaultJsonUnmarshaller.java:63) ~[json-unmarshaller-1.1.1.jar:?]

```

the usage is like this:

`@JsonPath("$")`

**Comment by kallestenflo** [comment]
I don't understand the issue. Can you provide an example?

Docs can be found here : https://github.com/jayway/JsonPath

**Comment by mahmutGuru** [comment]
sure, for ex:

```
class AAA {
    @JsonPath("$")
    private Map<String, Object> details;
}
```

when I do this, the exception occurs. In here, I just want the whole json as a Map in my class.

**Comment by kallestenflo** [comment]
This library does not have any annotations. You are targeting the wrong project. Check what package the annotation belongs to.

**Comment by jochenberger** [comment]
I guess this can be closed.
