### ISSUE TITLE
Can't be used in hive-0.11: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by followyourheart** [jayway/JsonPath#77]
The pom.xml was set according to your DOC: Getting Started.

I run it in my laptop, it works well. However, when run it on hive 0.11, error occurred:

Caused by: java.lang.NoClassDefFoundError: net/minidev/json/writer/JsonReaderI
        at com.jayway.jsonpath.internal.DefaultsImpl.<init>(DefaultsImpl.java:17)
        at com.jayway.jsonpath.internal.DefaultsImpl.<clinit>(DefaultsImpl.java:15)
        at com.jayway.jsonpath.Configuration.getEffectiveDefaults(Configuration.java:53)
        at com.jayway.jsonpath.Configuration.defaultConfiguration(Configuration.java:178)
        at com.jayway.jsonpath.internal.JsonReader.<init>(JsonReader.java:48)
        at com.jayway.jsonpath.JsonPath.read(JsonPath.java:461)
        at com.qunar.hive.udf.ParseJsonWithPath.evaluate(ParseJsonWithPath.java:64)
        ... 26 more
Caused by: java.lang.ClassNotFoundException: net.minidev.json.writer.JsonReaderI
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 33 more

Could anybody help me? Thanks a lot.

**Comment by kallestenflo** [comment]
Looks like you missing dependencies on your classpath. 

Try adding:
```
'net.minidev:json-smart:2.1.1'
'org.slf4j:slf4j-api:1.7.10'
```

**Comment by followyourheart** [comment]
Thanks a lot. I add the dependencies on my classpath following http://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.0.0

(
com.fasterxml.jackson.core    jackson-databind	2.4.5
com.google.code.gson           gson	                        2.3.1
net.minidev                             json-smart	                2.1.1
org.slf4j                                  slf4j-api	                1.7.10
)

A new error happened where querying on hive:
Caused by: java.lang.NoClassDefFoundError: com/jayway/jsonpath/Predicate
        at com.qunar.hive.udf.ParseJsonWithPath.evaluate(ParseJsonWithPath.java:58)
        ... 26 more
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.Predicate
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

Appreciate your help.

**Comment by kallestenflo** [comment]
Sorry, you also need `asm-1.0.2.jar` (json-smart dependency). Download the zip/tar with all dependencies here https://github.com/jayway/JsonPath/releases/tag/json-path-2.0.0. All jars under the `lib` folder are mandatory (if you use the default `JsonSmartJsonProvider`)

**Comment by followyourheart** [comment]
Thansk. But the same error occurred again.

.....
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.Predicate
....

**Comment by kallestenflo** [comment]
If you have the following jars on your classpath you're problem lies elsewhere. 
'net.minidev:json-smart:2.1.1'
'net.minidev:asm:2.1.1'
'org.slf4j:slf4j-api:1.7.10'
'com.jayway.jsonpath:json-path:2.0.0'
could it be you have multiple versions of jsonpath on CP? I don't know Hive.

**Comment by followyourheart** [comment]
Finally OK.

Using:
'net.minidev:json-smart:2.1.1'
'net.minidev:asm:1.0.2'
'org.slf4j:slf4j-api:1.7.10'
'com.jayway.jsonpath:json-path:2.0.0'

Thank you very much.

**Comment by zkendall** [comment]
Why aren't these dependencies included?
Shouldn't I only need to depend on json-path?

**Comment by kallestenflo** [comment]
They are if you use maven or gradle.

**Comment by zkendall** [comment]
I'm using maven. Had to explicitly define them.

**Comment by kallestenflo** [comment]
I just tested this again and it works. Does the attached project build?
[test-jp.zip](https://github.com/jayway/JsonPath/files/90033/test-jp.zip)

**Comment by kallestenflo** [comment]
@zkendall could you please verify if attached project builds.

**Comment by zkendall** [comment]
That worked fine.

**Comment by zkendall** [comment]
More details about my situation. I have a dependency on RestAssured.

```        <dependency>
            <groupId>com.jayway.restassured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured.version}</version>
            <scope>test</scope>
```
Which has a dependency on JsonPath. My IDE seemed to think everything was cool. But in run-time, I got NoClassDefFoundError.

To solve this, I had to add json-path and json-path-assert and json-smart (net.minidev) dependencies.

**Comment by JaguarXF** [comment]
I removed json-path version 0.9.1 and replaced it with json-path version 2.0.0 and this seemed to work for me.

**Comment by fuguanqi** [comment]
I was caught in the same problem when writing a UDTF parsing json. My solution was to put the jar package in path:$HIVE_HOME/lib.
