### ISSUE TITLE
Incorrect error message for JsonPath.read(Object)

### ISSUE THREAD

**Issue by mattj256** [jayway/JsonPath#89]
I am using JsonPath version 2.0.0.
I was trying to do this:

```
com.google.gson.JsonObject json = ...; // { "foo": "bar" }
JsonPath path = JsonPath.compile("$.foo");
String object = path.read(json);
```

**Actual behavior:**
```
    [junit] com.jayway.jsonpath.PathNotFoundException: Property ['foo'] not found in path $
    [junit] 	at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:41)
    [junit] 	at com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:53)
    [junit] 	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:53)
    [junit] 	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:61)
    [junit] 	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:178)
    [junit] 	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:155)
```

**Expected behavior:**
One of the following:
1. Throw ClassCastException
2. Error message that says: the document must be identified as either a List or Map by the JsonProvider.
3. call toString() on the object and try to parse the resulting String.

I find the current behavior to be very misleading: it makes it sound as though the problem is in the parameter to JsonPath.compile, when in fact the problem is in JsonPath.read.

**Comment by kallestenflo** [comment]
New stack trace  reads: 

```
com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['foo'] but found 'com.google.gson.JsonObject'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
	at com.jayway.jsonpath.internal.token.PropertyPathToken.evaluate(PropertyPathToken.java:42)
	at com.jayway.jsonpath.internal.token.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:51)
	at com.jayway.jsonpath.internal.CompiledPath.evaluate(CompiledPath.java:59)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:186)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:157)
	at com.jayway.jsonpath.old.IssuesTest.github_89(IssuesTest.java:887)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```
