### ISSUE TITLE
IndexOutOfBoundsException in DocumentContext.delete

### ISSUE THREAD

**Issue by fglez-tsl** [jayway/JsonPath#97]
Hi,

I am trying to remove some elements from an array. It usually works well, but there are times it throws an `IndexOutOfBoundsException`. Here is an example:
```
    @Test
    public void testName() throws Exception {
        String json = "{ \"books\": [ " +
                "{ \"category\": \"fiction\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"fiction\" }, " +
                "{ \"category\": \"fiction\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"fiction\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"reference\" }, " +
                "{ \"category\": \"reference\" } ]  }";
        Configuration conf = Configuration.builder()
                .jsonProvider(new GsonJsonProvider()).mappingProvider(new GsonMappingProvider()).build();
        DocumentContext context = JsonPath.using(conf).parse(json);
        context.delete("$.books[?(@.category == 'reference')]");
    }
```
```
java.lang.IndexOutOfBoundsException: Index: 10, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.google.gson.JsonArray.remove(JsonArray.java:106)
	at com.jayway.jsonpath.spi.json.GsonJsonProvider.removeProperty(GsonJsonProvider.java:184)
	at com.jayway.jsonpath.internal.PathRef$ArrayIndexPathRef.delete(PathRef.java:121)
	at com.jayway.jsonpath.JsonPath.delete(JsonPath.java:234)
	at com.jayway.jsonpath.internal.JsonReader.delete(JsonReader.java:204)
	at com.jayway.jsonpath.internal.JsonReader.delete(JsonReader.java:199)
[...]
```
It seems to me that `JsonPath.delete(Object, Configuration)` either is not updating the calculated indexes as it removes elements or it is not ordering the indexes from high to low.

Please let me know if you need more information.

Thank you.

**Comment by kallestenflo** [comment]
Fixed for 2.1.
